// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "7ae30058-b7ed-414e-8181-f9ef1f198626";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onSpeed01Change();
void onSpeed02Change();
void onStatus01Change();
void onStatus02Change();

float speed01;
float speed02;
bool status01;
bool status02;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(speed01, READWRITE, ON_CHANGE, onSpeed01Change);
  ArduinoCloud.addProperty(speed02, READWRITE, ON_CHANGE, onSpeed02Change);
  ArduinoCloud.addProperty(status01, READWRITE, ON_CHANGE, onStatus01Change);
  ArduinoCloud.addProperty(status02, READWRITE, ON_CHANGE, onStatus02Change);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
